name: exact-real
version: 0.12.3
synopsis: Exact real arithmetic
description: A type to represent exact real numbers using fast binary Cauchy sequences.
category: Math
author: Joe Hermaszewski
maintainer: Joe Hermaszewski <keep.it.real@monoid.al>
copyright: 2020 Joe Hermaszewski
github: expipiplus1/exact-real
extra-source-files:
- .gitignore
- readme.md
- stack.yaml
- default.nix
- changelog.md

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Data.CReal
  - Data.CReal.Converge
  - Data.CReal.Internal
  dependencies:
  - base >=4.8 && < 5
  - integer-gmp
  - memoize >=0.7
  - random >=1.0

tests:
  test:
    main: Test.hs
    other-modules:
    - BoundedFunctions
    - Data.CReal.Extra
    - Data.Monoid.Extra
    - Data.Ratio.Extra
    - Floating
    - Fractional
    - Num
    - Ord
    - Random
    - Read
    - Real
    - RealFloat
    - RealFrac
    - Test.QuickCheck.Classes.Extra
    - Test.QuickCheck.Extra
    - Test.Tasty.Extra
    - Paths_exact_real
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - base >=4
    - groups >=0.3
    - tasty >=0.10
    - tasty-th >=0.1
    - tasty-quickcheck >=0.8
    - tasty-hunit >=0.9
    - QuickCheck >=2.9
    - random >=1.0
    - checkers >=0.4 && <0.5.5
    - exact-real
    when:
        condition: impl(ghc < 8.0.0)
        buildable: false

  doctests:
    main: Doctests.hs
    other-modules: ""
    source-dirs:
      - test
    dependencies:
      - base
      - doctest

benchmarks:
  bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -Wall
    - -threaded
    - -O2
    dependencies:
    - base >=4
    - criterion >=1.1
    - exact-real

custom-setup:
 dependencies:
   - base
   - Cabal
   - cabal-doctest >= 1 && <1.1
