name: exact-real
version: 0.12.2
synopsis: Exact real arithmetic
description: A type to represent exact real numbers using fast binary Cauchy sequences.
category: Math
author: Joe Hermaszewski
maintainer: Joe Hermaszewski <keep.it.real@monoid.al>
copyright: 2015 Joe Hermaszewski
license: MIT
github: expipiplus1/exact-real
homepage: http://github.com/expipiplus1/exact-real
bug-reports: http://github.com/expipiplus1/exact-real/issues
tested-with: GHC>=7.10 && <=8.0.1
extra-source-files:
- .gitignore
- readme.md
- stack.yaml
- default.nix
- shell.nix

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Data.CReal
  - Data.CReal.Converge
  - Data.CReal.Internal
  dependencies:
  - base >=4.8 && <4.11
  - integer-gmp <1.1.0.0
  - memoize >=0.7 && <0.9
  - random >=1.0 && <1.2

tests:
  test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - base >=4 && <5
    - groups >=0.3 && <0.5
    - tasty >=0.10 && <0.12
    - tasty-th >=0.1 && <0.2
    - tasty-quickcheck >=0.8 && <0.9
    - tasty-hunit >=0.9 && <0.10
    - QuickCheck >=2.9 && <2.10
    - random >=1.0 && <1.2
    - checkers >=0.4 && <0.5
    - exact-real
  doctest:
    main: DocTest.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - base >=4 && <5
    - directory >=1.0 && <1.4
    - doctest >=0.8 && <0.12
    - filepath >=1.3 && <1.5

benchmarks:
  bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -Wall
    - -threaded
    - -O2
    dependencies:
    - base >=4 && <5
    - criterion >=1.1 && <1.2
    - exact-real
