name: exact-real
version: 0.12.2
synopsis: Exact real arithmetic
description: A type to represent exact real numbers using fast binary Cauchy sequences.
category: Math
author: Joe Hermaszewski
maintainer: Joe Hermaszewski <keep.it.real@monoid.al>
copyright: 2015 Joe Hermaszewski
license: MIT
github: expipiplus1/exact-real
homepage: http://github.com/expipiplus1/exact-real
bug-reports: http://github.com/expipiplus1/exact-real/issues
tested-with: GHC>=7.10 && <=8.0.1
extra-source-files:
- .gitignore
- readme.md
- stack.yaml
- default.nix
- shell.nix

library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - Data.CReal
  - Data.CReal.Converge
  - Data.CReal.Internal
  dependencies:
  - base >=4.8
  - integer-gmp
  - memoize >=0.7
  - random >=1.0

tests:
  test:
    main: Test.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - base >=4
    - groups >=0.3
    - tasty >=0.10
    - tasty-th >=0.1
    - tasty-quickcheck >=0.8
    - tasty-hunit >=0.9
    - QuickCheck >=2.9
    - random >=1.0
    - checkers >=0.4
    - exact-real
  doctest:
    main: DocTest.hs
    source-dirs: test
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - base >=4
    - directory >=1.0
    - doctest >=0.8
    - filepath >=1.3

benchmarks:
  bench:
    main: Bench.hs
    source-dirs: bench
    ghc-options:
    - -Wall
    - -threaded
    - -O2
    dependencies:
    - base >=4
    - criterion >=1.1
    - exact-real
