# Based on https://kodimensional.dev/github-actions

name: CI

# Trigger the workflow on push or pull request, but only for the master branch
on:
  pull_request:
  push:
    branches: [master]

env:
  cabalConfig: --enable-tests --enable-benchmarks --disable-optimization --enable-deterministic
    --write-ghc-environment-files=always

jobs:
  cabal:
    name: ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        cabal: [latest]
        ghc: ['8.6', '8.8', '8.10', '9.0']
      fail-fast: false

    steps:
    - uses: cachix/install-nix-action@v12
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: ${{ matrix.cabal }}

    - uses: actions/checkout@v2

    - name: Install system dependencies
      run: sudo apt-get install libsodium-dev

    - name: Install Nix dependencies
      run: nix-env -f '<nixpkgs>' -iA git nix-prefetch-git

    - name: Repository update
      run: |
        cabal v2-update

    # NOTE: Freeze is for the caching
    - name: Configuration freeze
      run: |
        cabal v2-freeze $cabalConfig

    - uses: actions/cache@v1
      name: Cache cabal-store
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze')
          }}
        restore-keys: ${{ runner.os }}-${{ matrix.ghc }}-

    - name: Build dependencies
      run: |
        cabal build all --only-dependencies $cabalConfig

    - name: Build
      run: |
        cabal build all $cabalConfig

    - name: Test
      run: |
        cabal test all $cabalConfig

    - name: Haddock
      if: ${{ matrix.ghc == '8.10' }}
      run: |
        cabal v2-haddock $cabalConfig

    - name: Source distribution file
      if: ${{ matrix.ghc == '8.10' }}
      run: |
        cabal v2-sdist


  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack: [2.1.3]
        ghc: [8.8.4]

    steps:
    - uses: actions/checkout@v2
      if: github.event.action == 'opened' || github.event.action == 'synchronize'
        || github.event.ref == 'refs/heads/master'

    - uses: haskell/actions/setup@v1
      id: setup-haskell-cabal
      name: Setup Haskell
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: ${{ matrix.stack }}

    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-${{ matrix.ghc }}-stack

    - name: Build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    - name: Test
      run: |
        stack test --system-ghc

  nix:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@v12
    - uses: actions/checkout@v2
    - run: |
        drvs=$(nix-instantiate | sed 's/!.*//')
        nix-build --no-out-link $drvs
